-- Speed4Card Import Script
SET NAMES utf8mb4;

-- Remove previous imports that used external hotlinked images
DELETE FROM goods WHERE picture LIKE 'https://www.speed4card.com%';


-- Category: iTunes,App Store充值
INSERT INTO goods_group (gp_name, is_open, ord) VALUES ('iTunes,App Store充值', 1, 1);
SET @cat_id_1 = LAST_INSERT_ID();
INSERT INTO goods (gd_name, gd_description, gd_keywords, picture, retail_price, actual_price, group_id, type, is_open) VALUES ('香港苹果App Store充值 | 香港iTunes充值礼品卡卡密 [自动发货] - 50 港币', '香港苹果App Store充值 | 香港iTunes充值礼品卡卡密 [自动发货] 本产品为香港苹果ID账号卡密充值，香港iTunes，香港App Store卡密充值。充值类型：官方卡密 自动发货如何发货：付款后1-5分钟，系统自动发货如何收货：请在会员中心--我的订单里--点击提取卡密进行充值。如何充值：iPad/iPhone端，香港iTunes苹果...', '香港苹果App Store充值 | 香港iTunes充值礼品卡卡密 [自动发货] - 50 港币', 'images/speed4card/bad1da31d251d1989e3629d6803a1c72.jpeg', 9.7, 9.7, @cat_id_1, 2, 1);
INSERT INTO goods (gd_name, gd_description, gd_keywords, picture, retail_price, actual_price, group_id, type, is_open) VALUES ('香港苹果App Store充值 | 香港iTunes充值礼品卡卡密 [自动发货] - 100 港币', '香港苹果App Store充值 | 香港iTunes充值礼品卡卡密 [自动发货] 本产品为香港苹果ID账号卡密充值，香港iTunes，香港App Store卡密充值。充值类型：官方卡密 自动发货如何发货：付款后1-5分钟，系统自动发货如何收货：请在会员中心--我的订单里--点击提取卡密进行充值。如何充值：iPad/iPhone端，香港iTunes苹果...', '香港苹果App Store充值 | 香港iTunes充值礼品卡卡密 [自动发货] - 100 港币', 'images/speed4card/bad1da31d251d1989e3629d6803a1c72.jpeg', 18.03, 18.03, @cat_id_1, 2, 1);
INSERT INTO goods (gd_name, gd_description, gd_keywords, picture, retail_price, actual_price, group_id, type, is_open) VALUES ('香港苹果App Store充值 | 香港iTunes充值礼品卡卡密 [自动发货] - 150 港币', '香港苹果App Store充值 | 香港iTunes充值礼品卡卡密 [自动发货] 本产品为香港苹果ID账号卡密充值，香港iTunes，香港App Store卡密充值。充值类型：官方卡密 自动发货如何发货：付款后1-5分钟，系统自动发货如何收货：请在会员中心--我的订单里--点击提取卡密进行充值。如何充值：iPad/iPhone端，香港iTunes苹果...', '香港苹果App Store充值 | 香港iTunes充值礼品卡卡密 [自动发货] - 150 港币', 'images/speed4card/bad1da31d251d1989e3629d6803a1c72.jpeg', 25.55, 25.55, @cat_id_1, 2, 1);
INSERT INTO goods (gd_name, gd_description, gd_keywords, picture, retail_price, actual_price, group_id, type, is_open) VALUES ('香港苹果App Store充值 | 香港iTunes充值礼品卡卡密 [自动发货] - 200 港币', '香港苹果App Store充值 | 香港iTunes充值礼品卡卡密 [自动发货] 本产品为香港苹果ID账号卡密充值，香港iTunes，香港App Store卡密充值。充值类型：官方卡密 自动发货如何发货：付款后1-5分钟，系统自动发货如何收货：请在会员中心--我的订单里--点击提取卡密进行充值。如何充值：iPad/iPhone端，香港iTunes苹果...', '香港苹果App Store充值 | 香港iTunes充值礼品卡卡密 [自动发货] - 200 港币', 'images/speed4card/bad1da31d251d1989e3629d6803a1c72.jpeg', 33.78, 33.78, @cat_id_1, 2, 1);
INSERT INTO goods (gd_name, gd_description, gd_keywords, picture, retail_price, actual_price, group_id, type, is_open) VALUES ('香港苹果App Store充值 | 香港iTunes充值礼品卡卡密 [自动发货] - 250 港币', '香港苹果App Store充值 | 香港iTunes充值礼品卡卡密 [自动发货] 本产品为香港苹果ID账号卡密充值，香港iTunes，香港App Store卡密充值。充值类型：官方卡密 自动发货如何发货：付款后1-5分钟，系统自动发货如何收货：请在会员中心--我的订单里--点击提取卡密进行充值。如何充值：iPad/iPhone端，香港iTunes苹果...', '香港苹果App Store充值 | 香港iTunes充值礼品卡卡密 [自动发货] - 250 港币', 'images/speed4card/bad1da31d251d1989e3629d6803a1c72.jpeg', 42.01, 42.01, @cat_id_1, 2, 1);
INSERT INTO goods (gd_name, gd_description, gd_keywords, picture, retail_price, actual_price, group_id, type, is_open) VALUES ('香港苹果App Store充值 | 香港iTunes充值礼品卡卡密 [自动发货] - 300 港币', '香港苹果App Store充值 | 香港iTunes充值礼品卡卡密 [自动发货] 本产品为香港苹果ID账号卡密充值，香港iTunes，香港App Store卡密充值。充值类型：官方卡密 自动发货如何发货：付款后1-5分钟，系统自动发货如何收货：请在会员中心--我的订单里--点击提取卡密进行充值。如何充值：iPad/iPhone端，香港iTunes苹果...', '香港苹果App Store充值 | 香港iTunes充值礼品卡卡密 [自动发货] - 300 港币', 'images/speed4card/bad1da31d251d1989e3629d6803a1c72.jpeg', 50.59, 50.59, @cat_id_1, 2, 1);
INSERT INTO goods (gd_name, gd_description, gd_keywords, picture, retail_price, actual_price, group_id, type, is_open) VALUES ('香港苹果App Store充值 | 香港iTunes充值礼品卡卡密 [自动发货] - 500 港币', '香港苹果App Store充值 | 香港iTunes充值礼品卡卡密 [自动发货] 本产品为香港苹果ID账号卡密充值，香港iTunes，香港App Store卡密充值。充值类型：官方卡密 自动发货如何发货：付款后1-5分钟，系统自动发货如何收货：请在会员中心--我的订单里--点击提取卡密进行充值。如何充值：iPad/iPhone端，香港iTunes苹果...', '香港苹果App Store充值 | 香港iTunes充值礼品卡卡密 [自动发货] - 500 港币', 'images/speed4card/bad1da31d251d1989e3629d6803a1c72.jpeg', 82.62, 82.62, @cat_id_1, 2, 1);
INSERT INTO goods (gd_name, gd_description, gd_keywords, picture, retail_price, actual_price, group_id, type, is_open) VALUES ('香港苹果App Store充值 | 香港iTunes充值礼品卡卡密 [自动发货] - 788 港币', '香港苹果App Store充值 | 香港iTunes充值礼品卡卡密 [自动发货] 本产品为香港苹果ID账号卡密充值，香港iTunes，香港App Store卡密充值。充值类型：官方卡密 自动发货如何发货：付款后1-5分钟，系统自动发货如何收货：请在会员中心--我的订单里--点击提取卡密进行充值。如何充值：iPad/iPhone端，香港iTunes苹果...', '香港苹果App Store充值 | 香港iTunes充值礼品卡卡密 [自动发货] - 788 港币', 'images/speed4card/bad1da31d251d1989e3629d6803a1c72.jpeg', 134.79, 134.79, @cat_id_1, 2, 1);
INSERT INTO goods (gd_name, gd_description, gd_keywords, picture, retail_price, actual_price, group_id, type, is_open) VALUES ('香港苹果App Store充值 | 香港iTunes充值礼品卡卡密 [自动发货] - 1000港币', '香港苹果App Store充值 | 香港iTunes充值礼品卡卡密 [自动发货] 本产品为香港苹果ID账号卡密充值，香港iTunes，香港App Store卡密充值。充值类型：官方卡密 自动发货如何发货：付款后1-5分钟，系统自动发货如何收货：请在会员中心--我的订单里--点击提取卡密进行充值。如何充值：iPad/iPhone端，香港iTunes苹果...', '香港苹果App Store充值 | 香港iTunes充值礼品卡卡密 [自动发货] - 1000港币', 'images/speed4card/bad1da31d251d1989e3629d6803a1c72.jpeg', 164.55, 164.55, @cat_id_1, 2, 1);
INSERT INTO goods (gd_name, gd_description, gd_keywords, picture, retail_price, actual_price, group_id, type, is_open) VALUES ('香港苹果App Store充值 | 香港iTunes充值礼品卡卡密 [自动发货] - 1500 港币', '香港苹果App Store充值 | 香港iTunes充值礼品卡卡密 [自动发货] 本产品为香港苹果ID账号卡密充值，香港iTunes，香港App Store卡密充值。充值类型：官方卡密 自动发货如何发货：付款后1-5分钟，系统自动发货如何收货：请在会员中心--我的订单里--点击提取卡密进行充值。如何充值：iPad/iPhone端，香港iTunes苹果...', '香港苹果App Store充值 | 香港iTunes充值礼品卡卡密 [自动发货] - 1500 港币', 'images/speed4card/bad1da31d251d1989e3629d6803a1c72.jpeg', 246.3, 246.3, @cat_id_1, 2, 1);
INSERT INTO goods (gd_name, gd_description, gd_keywords, picture, retail_price, actual_price, group_id, type, is_open) VALUES ('香港苹果App Store充值 | 香港iTunes充值礼品卡卡密 [自动发货] - 2000 港币', '香港苹果App Store充值 | 香港iTunes充值礼品卡卡密 [自动发货] 本产品为香港苹果ID账号卡密充值，香港iTunes，香港App Store卡密充值。充值类型：官方卡密 自动发货如何发货：付款后1-5分钟，系统自动发货如何收货：请在会员中心--我的订单里--点击提取卡密进行充值。如何充值：iPad/iPhone端，香港iTunes苹果...', '香港苹果App Store充值 | 香港iTunes充值礼品卡卡密 [自动发货] - 2000 港币', 'images/speed4card/bad1da31d251d1989e3629d6803a1c72.jpeg', 328.76, 328.76, @cat_id_1, 2, 1);
INSERT INTO goods (gd_name, gd_description, gd_keywords, picture, retail_price, actual_price, group_id, type, is_open) VALUES ('香港苹果App Store充值 | 香港iTunes充值礼品卡卡密 [自动发货] - 4000 港币', '香港苹果App Store充值 | 香港iTunes充值礼品卡卡密 [自动发货] 本产品为香港苹果ID账号卡密充值，香港iTunes，香港App Store卡密充值。充值类型：官方卡密 自动发货如何发货：付款后1-5分钟，系统自动发货如何收货：请在会员中心--我的订单里--点击提取卡密进行充值。如何充值：iPad/iPhone端，香港iTunes苹果...', '香港苹果App Store充值 | 香港iTunes充值礼品卡卡密 [自动发货] - 4000 港币', 'images/speed4card/bad1da31d251d1989e3629d6803a1c72.jpeg', 650.49, 650.49, @cat_id_1, 2, 1);
INSERT INTO goods (gd_name, gd_description, gd_keywords, picture, retail_price, actual_price, group_id, type, is_open) VALUES ('台湾苹果App Store充值 | 台湾iTunes充值礼品卡卡密 [自动发货] - 100 台币', '台湾苹果App Store充值 | 台湾iTunes充值礼品卡卡密 [自动发货] 本产品为台湾苹果ID账号卡密充值，台湾iTunes，台湾App Store卡密充值充值类型：官方卡密 自动发货如何收货：会员中心&rarr;我的订单&rarr;点击提取卡密，自助绑定至苹果账户如何充值：iPad/iPhone端，台湾iTunes苹果App Store卡密充值激活方法：...', '台湾苹果App Store充值 | 台湾iTunes充值礼品卡卡密 [自动发货] - 100 台币', 'images/speed4card/45204d129c34c4654d41186cad176c1d.jpeg', 4.77, 4.77, @cat_id_1, 2, 1);
INSERT INTO goods (gd_name, gd_description, gd_keywords, picture, retail_price, actual_price, group_id, type, is_open) VALUES ('台湾苹果App Store充值 | 台湾iTunes充值礼品卡卡密 [自动发货] - 200 台币', '台湾苹果App Store充值 | 台湾iTunes充值礼品卡卡密 [自动发货] 本产品为台湾苹果ID账号卡密充值，台湾iTunes，台湾App Store卡密充值充值类型：官方卡密 自动发货如何收货：会员中心&rarr;我的订单&rarr;点击提取卡密，自助绑定至苹果账户如何充值：iPad/iPhone端，台湾iTunes苹果App Store卡密充值激活方法：...', '台湾苹果App Store充值 | 台湾iTunes充值礼品卡卡密 [自动发货] - 200 台币', 'images/speed4card/45204d129c34c4654d41186cad176c1d.jpeg', 9.36, 9.36, @cat_id_1, 2, 1);
INSERT INTO goods (gd_name, gd_description, gd_keywords, picture, retail_price, actual_price, group_id, type, is_open) VALUES ('台湾苹果App Store充值 | 台湾iTunes充值礼品卡卡密 [自动发货] - 300 台币', '台湾苹果App Store充值 | 台湾iTunes充值礼品卡卡密 [自动发货] 本产品为台湾苹果ID账号卡密充值，台湾iTunes，台湾App Store卡密充值充值类型：官方卡密 自动发货如何收货：会员中心&rarr;我的订单&rarr;点击提取卡密，自助绑定至苹果账户如何充值：iPad/iPhone端，台湾iTunes苹果App Store卡密充值激活方法：...', '台湾苹果App Store充值 | 台湾iTunes充值礼品卡卡密 [自动发货] - 300 台币', 'images/speed4card/45204d129c34c4654d41186cad176c1d.jpeg', 12.44, 12.44, @cat_id_1, 2, 1);
INSERT INTO goods (gd_name, gd_description, gd_keywords, picture, retail_price, actual_price, group_id, type, is_open) VALUES ('台湾苹果App Store充值 | 台湾iTunes充值礼品卡卡密 [自动发货] - 500 台币', '台湾苹果App Store充值 | 台湾iTunes充值礼品卡卡密 [自动发货] 本产品为台湾苹果ID账号卡密充值，台湾iTunes，台湾App Store卡密充值充值类型：官方卡密 自动发货如何收货：会员中心&rarr;我的订单&rarr;点击提取卡密，自助绑定至苹果账户如何充值：iPad/iPhone端，台湾iTunes苹果App Store卡密充值激活方法：...', '台湾苹果App Store充值 | 台湾iTunes充值礼品卡卡密 [自动发货] - 500 台币', 'images/speed4card/45204d129c34c4654d41186cad176c1d.jpeg', 19.6, 19.6, @cat_id_1, 2, 1);
INSERT INTO goods (gd_name, gd_description, gd_keywords, picture, retail_price, actual_price, group_id, type, is_open) VALUES ('台湾苹果App Store充值 | 台湾iTunes充值礼品卡卡密 [自动发货] - 1000 台币', '台湾苹果App Store充值 | 台湾iTunes充值礼品卡卡密 [自动发货] 本产品为台湾苹果ID账号卡密充值，台湾iTunes，台湾App Store卡密充值充值类型：官方卡密 自动发货如何收货：会员中心&rarr;我的订单&rarr;点击提取卡密，自助绑定至苹果账户如何充值：iPad/iPhone端，台湾iTunes苹果App Store卡密充值激活方法：...', '台湾苹果App Store充值 | 台湾iTunes充值礼品卡卡密 [自动发货] - 1000 台币', 'images/speed4card/45204d129c34c4654d41186cad176c1d.jpeg', 39.22, 39.22, @cat_id_1, 2, 1);
INSERT INTO goods (gd_name, gd_description, gd_keywords, picture, retail_price, actual_price, group_id, type, is_open) VALUES ('台湾苹果App Store充值 | 台湾iTunes充值礼品卡卡密 [自动发货] - 2000 台币', '台湾苹果App Store充值 | 台湾iTunes充值礼品卡卡密 [自动发货] 本产品为台湾苹果ID账号卡密充值，台湾iTunes，台湾App Store卡密充值充值类型：官方卡密 自动发货如何收货：会员中心&rarr;我的订单&rarr;点击提取卡密，自助绑定至苹果账户如何充值：iPad/iPhone端，台湾iTunes苹果App Store卡密充值激活方法：...', '台湾苹果App Store充值 | 台湾iTunes充值礼品卡卡密 [自动发货] - 2000 台币', 'images/speed4card/45204d129c34c4654d41186cad176c1d.jpeg', 78.77, 78.77, @cat_id_1, 2, 1);
INSERT INTO goods (gd_name, gd_description, gd_keywords, picture, retail_price, actual_price, group_id, type, is_open) VALUES ('台湾苹果App Store充值 | 台湾iTunes充值礼品卡卡密 [自动发货] - 3000 台币', '台湾苹果App Store充值 | 台湾iTunes充值礼品卡卡密 [自动发货] 本产品为台湾苹果ID账号卡密充值，台湾iTunes，台湾App Store卡密充值充值类型：官方卡密 自动发货如何收货：会员中心&rarr;我的订单&rarr;点击提取卡密，自助绑定至苹果账户如何充值：iPad/iPhone端，台湾iTunes苹果App Store卡密充值激活方法：...', '台湾苹果App Store充值 | 台湾iTunes充值礼品卡卡密 [自动发货] - 3000 台币', 'images/speed4card/45204d129c34c4654d41186cad176c1d.jpeg', 118.16, 118.16, @cat_id_1, 2, 1);
INSERT INTO goods (gd_name, gd_description, gd_keywords, picture, retail_price, actual_price, group_id, type, is_open) VALUES ('台湾苹果App Store充值 | 台湾iTunes充值礼品卡卡密 [自动发货] - 5000 台币', '台湾苹果App Store充值 | 台湾iTunes充值礼品卡卡密 [自动发货] 本产品为台湾苹果ID账号卡密充值，台湾iTunes，台湾App Store卡密充值充值类型：官方卡密 自动发货如何收货：会员中心&rarr;我的订单&rarr;点击提取卡密，自助绑定至苹果账户如何充值：iPad/iPhone端，台湾iTunes苹果App Store卡密充值激活方法：...', '台湾苹果App Store充值 | 台湾iTunes充值礼品卡卡密 [自动发货] - 5000 台币', 'images/speed4card/45204d129c34c4654d41186cad176c1d.jpeg', 196.93, 196.93, @cat_id_1, 2, 1);
INSERT INTO goods (gd_name, gd_description, gd_keywords, picture, retail_price, actual_price, group_id, type, is_open) VALUES ('台湾苹果App Store充值 | 台湾iTunes充值礼品卡卡密 [自动发货] - 6000 台币', '台湾苹果App Store充值 | 台湾iTunes充值礼品卡卡密 [自动发货] 本产品为台湾苹果ID账号卡密充值，台湾iTunes，台湾App Store卡密充值充值类型：官方卡密 自动发货如何收货：会员中心&rarr;我的订单&rarr;点击提取卡密，自助绑定至苹果账户如何充值：iPad/iPhone端，台湾iTunes苹果App Store卡密充值激活方法：...', '台湾苹果App Store充值 | 台湾iTunes充值礼品卡卡密 [自动发货] - 6000 台币', 'images/speed4card/45204d129c34c4654d41186cad176c1d.jpeg', 236.32, 236.32, @cat_id_1, 2, 1);
INSERT INTO goods (gd_name, gd_description, gd_keywords, picture, retail_price, actual_price, group_id, type, is_open) VALUES ('台湾苹果App Store充值 | 台湾iTunes充值礼品卡卡密 [自动发货] - 50 台币', '台湾苹果App Store充值 | 台湾iTunes充值礼品卡卡密 [自动发货] 本产品为台湾苹果ID账号卡密充值，台湾iTunes，台湾App Store卡密充值充值类型：官方卡密 自动发货如何收货：会员中心&rarr;我的订单&rarr;点击提取卡密，自助绑定至苹果账户如何充值：iPad/iPhone端，台湾iTunes苹果App Store卡密充值激活方法：...', '台湾苹果App Store充值 | 台湾iTunes充值礼品卡卡密 [自动发货] - 50 台币', 'images/speed4card/45204d129c34c4654d41186cad176c1d.jpeg', 2.23, 2.23, @cat_id_1, 2, 1);

-- Category: 全球礼品卡
INSERT INTO goods_group (gp_name, is_open, ord) VALUES ('全球礼品卡', 1, 1);
SET @cat_id_2 = LAST_INSERT_ID();

-- Category: 国际服游戏代充值
INSERT INTO goods_group (gp_name, is_open, ord) VALUES ('国际服游戏代充值', 1, 1);
SET @cat_id_3 = LAST_INSERT_ID();

-- Category: 全球网站AI代购代付
INSERT INTO goods_group (gp_name, is_open, ord) VALUES ('全球网站AI代购代付', 1, 1);
SET @cat_id_4 = LAST_INSERT_ID();

-- Category: TV视频会员充值
INSERT INTO goods_group (gp_name, is_open, ord) VALUES ('TV视频会员充值', 1, 1);
SET @cat_id_5 = LAST_INSERT_ID();

-- Category: 直播小视频充值
INSERT INTO goods_group (gp_name, is_open, ord) VALUES ('直播小视频充值', 1, 1);
SET @cat_id_6 = LAST_INSERT_ID();
INSERT INTO goods (gd_name, gd_description, gd_keywords, picture, retail_price, actual_price, group_id, type, is_open) VALUES ('Youtube premium 油管个人会员 家庭会员 频道订阅 [人工代充] - 个人会员一个月', 'Youtube premium 油管个人会员 家庭会员 频道订阅 [人工代充] 本产品为：Youtube premium 油管个人会员充值代购。发货方式：人工代充YouTube个人会员怎么充值？提供账号密码+备用码，客服上号代充。YouTube家庭会员怎么充值？1. 无需登录账号，只需提供YouTube邮箱，给您发邀请邮件；2. 收到邮件后，点击加...', 'Youtube premium 油管个人会员 家庭会员 频道订阅 [人工代充] - 个人会员一个月', 'images/speed4card/c194f272ce2405e8121ded5940e3537d.png', 8.59, 8.59, @cat_id_6, 2, 1);
INSERT INTO goods (gd_name, gd_description, gd_keywords, picture, retail_price, actual_price, group_id, type, is_open) VALUES ('Youtube premium 油管个人会员 家庭会员 频道订阅 [人工代充] - 家庭会员一个月', 'Youtube premium 油管个人会员 家庭会员 频道订阅 [人工代充] 本产品为：Youtube premium 油管个人会员充值代购。发货方式：人工代充YouTube个人会员怎么充值？提供账号密码+备用码，客服上号代充。YouTube家庭会员怎么充值？1. 无需登录账号，只需提供YouTube邮箱，给您发邀请邮件；2. 收到邮件后，点击加...', 'Youtube premium 油管个人会员 家庭会员 频道订阅 [人工代充] - 家庭会员一个月', 'images/speed4card/c194f272ce2405e8121ded5940e3537d.png', 5.73, 5.73, @cat_id_6, 2, 1);
INSERT INTO goods (gd_name, gd_description, gd_keywords, picture, retail_price, actual_price, group_id, type, is_open) VALUES ('Youtube premium 油管个人会员 家庭会员 频道订阅 [人工代充] - 家庭会员独享一个月', 'Youtube premium 油管个人会员 家庭会员 频道订阅 [人工代充] 本产品为：Youtube premium 油管个人会员充值代购。发货方式：人工代充YouTube个人会员怎么充值？提供账号密码+备用码，客服上号代充。YouTube家庭会员怎么充值？1. 无需登录账号，只需提供YouTube邮箱，给您发邀请邮件；2. 收到邮件后，点击加...', 'Youtube premium 油管个人会员 家庭会员 频道订阅 [人工代充] - 家庭会员独享一个月', 'images/speed4card/c194f272ce2405e8121ded5940e3537d.png', 14.64, 14.64, @cat_id_6, 2, 1);
INSERT INTO goods (gd_name, gd_description, gd_keywords, picture, retail_price, actual_price, group_id, type, is_open) VALUES ('Youtube premium 油管个人会员 家庭会员 频道订阅 [人工代充] - 其他频道联系客服', 'Youtube premium 油管个人会员 家庭会员 频道订阅 [人工代充] 本产品为：Youtube premium 油管个人会员充值代购。发货方式：人工代充YouTube个人会员怎么充值？提供账号密码+备用码，客服上号代充。YouTube家庭会员怎么充值？1. 无需登录账号，只需提供YouTube邮箱，给您发邀请邮件；2. 收到邮件后，点击加...', 'Youtube premium 油管个人会员 家庭会员 频道订阅 [人工代充] - 其他频道联系客服', 'images/speed4card/c194f272ce2405e8121ded5940e3537d.png', 0.19, 0.19, @cat_id_6, 2, 1);
INSERT INTO goods (gd_name, gd_description, gd_keywords, picture, retail_price, actual_price, group_id, type, is_open) VALUES ('Youtube premium 油管个人会员 家庭会员 频道订阅 [人工代充] - 任意金额', 'Youtube premium 油管个人会员 家庭会员 频道订阅 [人工代充] 本产品为：Youtube premium 油管个人会员充值代购。发货方式：人工代充YouTube个人会员怎么充值？提供账号密码+备用码，客服上号代充。YouTube家庭会员怎么充值？1. 无需登录账号，只需提供YouTube邮箱，给您发邀请邮件；2. 收到邮件后，点击加...', 'Youtube premium 油管个人会员 家庭会员 频道订阅 [人工代充] - 任意金额', 'images/speed4card/c194f272ce2405e8121ded5940e3537d.png', 0.19, 0.19, @cat_id_6, 2, 1);
INSERT INTO goods (gd_name, gd_description, gd_keywords, picture, retail_price, actual_price, group_id, type, is_open) VALUES ('BIGO LIVE直播充值 bigolive钻石代充 [自动充值] - 50 钻石', 'BIGO LIVE直播充值 bigolive钻石代充 [自动充值] 此产品为：BIGO LIVE直播钻石充值，BIGO钻石只能用于直播间送礼物。充值类型：系统自动充值如何发货：付款后1-5分钟内，系统自动充值【BIGO钻石充值】如何收货：登入BIGO LIVE直播，查看钻石余额和明细【BIGO钻石充值】注意事项：1. 购买前请确...', 'BIGO LIVE直播充值 bigolive钻石代充 [自动充值] - 50 钻石', 'images/speed4card/c26c864ec279d1fae9f418110fcd54bd.jpeg', 1.34, 1.34, @cat_id_6, 2, 1);
INSERT INTO goods (gd_name, gd_description, gd_keywords, picture, retail_price, actual_price, group_id, type, is_open) VALUES ('BIGO LIVE直播充值 bigolive钻石代充 [自动充值] - 100 钻石', 'BIGO LIVE直播充值 bigolive钻石代充 [自动充值] 此产品为：BIGO LIVE直播钻石充值，BIGO钻石只能用于直播间送礼物。充值类型：系统自动充值如何发货：付款后1-5分钟内，系统自动充值【BIGO钻石充值】如何收货：登入BIGO LIVE直播，查看钻石余额和明细【BIGO钻石充值】注意事项：1. 购买前请确...', 'BIGO LIVE直播充值 bigolive钻石代充 [自动充值] - 100 钻石', 'images/speed4card/c26c864ec279d1fae9f418110fcd54bd.jpeg', 2.68, 2.68, @cat_id_6, 2, 1);
INSERT INTO goods (gd_name, gd_description, gd_keywords, picture, retail_price, actual_price, group_id, type, is_open) VALUES ('BIGO LIVE直播充值 bigolive钻石代充 [自动充值] - 160 钻石', 'BIGO LIVE直播充值 bigolive钻石代充 [自动充值] 此产品为：BIGO LIVE直播钻石充值，BIGO钻石只能用于直播间送礼物。充值类型：系统自动充值如何发货：付款后1-5分钟内，系统自动充值【BIGO钻石充值】如何收货：登入BIGO LIVE直播，查看钻石余额和明细【BIGO钻石充值】注意事项：1. 购买前请确...', 'BIGO LIVE直播充值 bigolive钻石代充 [自动充值] - 160 钻石', 'images/speed4card/c26c864ec279d1fae9f418110fcd54bd.jpeg', 4.3, 4.3, @cat_id_6, 2, 1);
INSERT INTO goods (gd_name, gd_description, gd_keywords, picture, retail_price, actual_price, group_id, type, is_open) VALUES ('BIGO LIVE直播充值 bigolive钻石代充 [自动充值] - 200 钻石', 'BIGO LIVE直播充值 bigolive钻石代充 [自动充值] 此产品为：BIGO LIVE直播钻石充值，BIGO钻石只能用于直播间送礼物。充值类型：系统自动充值如何发货：付款后1-5分钟内，系统自动充值【BIGO钻石充值】如何收货：登入BIGO LIVE直播，查看钻石余额和明细【BIGO钻石充值】注意事项：1. 购买前请确...', 'BIGO LIVE直播充值 bigolive钻石代充 [自动充值] - 200 钻石', 'images/speed4card/c26c864ec279d1fae9f418110fcd54bd.jpeg', 5.18, 5.18, @cat_id_6, 2, 1);
INSERT INTO goods (gd_name, gd_description, gd_keywords, picture, retail_price, actual_price, group_id, type, is_open) VALUES ('BIGO LIVE直播充值 bigolive钻石代充 [自动充值] - 240 钻石', 'BIGO LIVE直播充值 bigolive钻石代充 [自动充值] 此产品为：BIGO LIVE直播钻石充值，BIGO钻石只能用于直播间送礼物。充值类型：系统自动充值如何发货：付款后1-5分钟内，系统自动充值【BIGO钻石充值】如何收货：登入BIGO LIVE直播，查看钻石余额和明细【BIGO钻石充值】注意事项：1. 购买前请确...', 'BIGO LIVE直播充值 bigolive钻石代充 [自动充值] - 240 钻石', 'images/speed4card/c26c864ec279d1fae9f418110fcd54bd.jpeg', 6.45, 6.45, @cat_id_6, 2, 1);
INSERT INTO goods (gd_name, gd_description, gd_keywords, picture, retail_price, actual_price, group_id, type, is_open) VALUES ('BIGO LIVE直播充值 bigolive钻石代充 [自动充值] - 400 钻石', 'BIGO LIVE直播充值 bigolive钻石代充 [自动充值] 此产品为：BIGO LIVE直播钻石充值，BIGO钻石只能用于直播间送礼物。充值类型：系统自动充值如何发货：付款后1-5分钟内，系统自动充值【BIGO钻石充值】如何收货：登入BIGO LIVE直播，查看钻石余额和明细【BIGO钻石充值】注意事项：1. 购买前请确...', 'BIGO LIVE直播充值 bigolive钻石代充 [自动充值] - 400 钻石', 'images/speed4card/c26c864ec279d1fae9f418110fcd54bd.jpeg', 10.3, 10.3, @cat_id_6, 2, 1);
INSERT INTO goods (gd_name, gd_description, gd_keywords, picture, retail_price, actual_price, group_id, type, is_open) VALUES ('BIGO LIVE直播充值 bigolive钻石代充 [自动充值] - 500 钻石', 'BIGO LIVE直播充值 bigolive钻石代充 [自动充值] 此产品为：BIGO LIVE直播钻石充值，BIGO钻石只能用于直播间送礼物。充值类型：系统自动充值如何发货：付款后1-5分钟内，系统自动充值【BIGO钻石充值】如何收货：登入BIGO LIVE直播，查看钻石余额和明细【BIGO钻石充值】注意事项：1. 购买前请确...', 'BIGO LIVE直播充值 bigolive钻石代充 [自动充值] - 500 钻石', 'images/speed4card/c26c864ec279d1fae9f418110fcd54bd.jpeg', 12.86, 12.86, @cat_id_6, 2, 1);
INSERT INTO goods (gd_name, gd_description, gd_keywords, picture, retail_price, actual_price, group_id, type, is_open) VALUES ('BIGO LIVE直播充值 bigolive钻石代充 [自动充值] - 800 钻石', 'BIGO LIVE直播充值 bigolive钻石代充 [自动充值] 此产品为：BIGO LIVE直播钻石充值，BIGO钻石只能用于直播间送礼物。充值类型：系统自动充值如何发货：付款后1-5分钟内，系统自动充值【BIGO钻石充值】如何收货：登入BIGO LIVE直播，查看钻石余额和明细【BIGO钻石充值】注意事项：1. 购买前请确...', 'BIGO LIVE直播充值 bigolive钻石代充 [自动充值] - 800 钻石', 'images/speed4card/c26c864ec279d1fae9f418110fcd54bd.jpeg', 19.7, 19.7, @cat_id_6, 2, 1);
INSERT INTO goods (gd_name, gd_description, gd_keywords, picture, retail_price, actual_price, group_id, type, is_open) VALUES ('BIGO LIVE直播充值 bigolive钻石代充 [自动充值] - 1000 钻石', 'BIGO LIVE直播充值 bigolive钻石代充 [自动充值] 此产品为：BIGO LIVE直播钻石充值，BIGO钻石只能用于直播间送礼物。充值类型：系统自动充值如何发货：付款后1-5分钟内，系统自动充值【BIGO钻石充值】如何收货：登入BIGO LIVE直播，查看钻石余额和明细【BIGO钻石充值】注意事项：1. 购买前请确...', 'BIGO LIVE直播充值 bigolive钻石代充 [自动充值] - 1000 钻石', 'images/speed4card/c26c864ec279d1fae9f418110fcd54bd.jpeg', 24.63, 24.63, @cat_id_6, 2, 1);
INSERT INTO goods (gd_name, gd_description, gd_keywords, picture, retail_price, actual_price, group_id, type, is_open) VALUES ('BIGO LIVE直播充值 bigolive钻石代充 [自动充值] - 2000 钻石', 'BIGO LIVE直播充值 bigolive钻石代充 [自动充值] 此产品为：BIGO LIVE直播钻石充值，BIGO钻石只能用于直播间送礼物。充值类型：系统自动充值如何发货：付款后1-5分钟内，系统自动充值【BIGO钻石充值】如何收货：登入BIGO LIVE直播，查看钻石余额和明细【BIGO钻石充值】注意事项：1. 购买前请确...', 'BIGO LIVE直播充值 bigolive钻石代充 [自动充值] - 2000 钻石', 'images/speed4card/c26c864ec279d1fae9f418110fcd54bd.jpeg', 49.26, 49.26, @cat_id_6, 2, 1);
INSERT INTO goods (gd_name, gd_description, gd_keywords, picture, retail_price, actual_price, group_id, type, is_open) VALUES ('BIGO LIVE直播充值 bigolive钻石代充 [自动充值] - 3000 钻石', 'BIGO LIVE直播充值 bigolive钻石代充 [自动充值] 此产品为：BIGO LIVE直播钻石充值，BIGO钻石只能用于直播间送礼物。充值类型：系统自动充值如何发货：付款后1-5分钟内，系统自动充值【BIGO钻石充值】如何收货：登入BIGO LIVE直播，查看钻石余额和明细【BIGO钻石充值】注意事项：1. 购买前请确...', 'BIGO LIVE直播充值 bigolive钻石代充 [自动充值] - 3000 钻石', 'images/speed4card/c26c864ec279d1fae9f418110fcd54bd.jpeg', 71.42, 71.42, @cat_id_6, 2, 1);
INSERT INTO goods (gd_name, gd_description, gd_keywords, picture, retail_price, actual_price, group_id, type, is_open) VALUES ('BIGO LIVE直播充值 bigolive钻石代充 [自动充值] - 4000 钻石', 'BIGO LIVE直播充值 bigolive钻石代充 [自动充值] 此产品为：BIGO LIVE直播钻石充值，BIGO钻石只能用于直播间送礼物。充值类型：系统自动充值如何发货：付款后1-5分钟内，系统自动充值【BIGO钻石充值】如何收货：登入BIGO LIVE直播，查看钻石余额和明细【BIGO钻石充值】注意事项：1. 购买前请确...', 'BIGO LIVE直播充值 bigolive钻石代充 [自动充值] - 4000 钻石', 'images/speed4card/c26c864ec279d1fae9f418110fcd54bd.jpeg', 98.52, 98.52, @cat_id_6, 2, 1);
INSERT INTO goods (gd_name, gd_description, gd_keywords, picture, retail_price, actual_price, group_id, type, is_open) VALUES ('BIGO LIVE直播充值 bigolive钻石代充 [自动充值] - 5000 钻石', 'BIGO LIVE直播充值 bigolive钻石代充 [自动充值] 此产品为：BIGO LIVE直播钻石充值，BIGO钻石只能用于直播间送礼物。充值类型：系统自动充值如何发货：付款后1-5分钟内，系统自动充值【BIGO钻石充值】如何收货：登入BIGO LIVE直播，查看钻石余额和明细【BIGO钻石充值】注意事项：1. 购买前请确...', 'BIGO LIVE直播充值 bigolive钻石代充 [自动充值] - 5000 钻石', 'images/speed4card/c26c864ec279d1fae9f418110fcd54bd.jpeg', 119.04, 119.04, @cat_id_6, 2, 1);
INSERT INTO goods (gd_name, gd_description, gd_keywords, picture, retail_price, actual_price, group_id, type, is_open) VALUES ('BIGO LIVE直播充值 bigolive钻石代充 [自动充值] - 8000 钻石', 'BIGO LIVE直播充值 bigolive钻石代充 [自动充值] 此产品为：BIGO LIVE直播钻石充值，BIGO钻石只能用于直播间送礼物。充值类型：系统自动充值如何发货：付款后1-5分钟内，系统自动充值【BIGO钻石充值】如何收货：登入BIGO LIVE直播，查看钻石余额和明细【BIGO钻石充值】注意事项：1. 购买前请确...', 'BIGO LIVE直播充值 bigolive钻石代充 [自动充值] - 8000 钻石', 'images/speed4card/c26c864ec279d1fae9f418110fcd54bd.jpeg', 196.93, 196.93, @cat_id_6, 2, 1);
INSERT INTO goods (gd_name, gd_description, gd_keywords, picture, retail_price, actual_price, group_id, type, is_open) VALUES ('BIGO LIVE直播充值 bigolive钻石代充 [自动充值] - 10000 钻石', 'BIGO LIVE直播充值 bigolive钻石代充 [自动充值] 此产品为：BIGO LIVE直播钻石充值，BIGO钻石只能用于直播间送礼物。充值类型：系统自动充值如何发货：付款后1-5分钟内，系统自动充值【BIGO钻石充值】如何收货：登入BIGO LIVE直播，查看钻石余额和明细【BIGO钻石充值】注意事项：1. 购买前请确...', 'BIGO LIVE直播充值 bigolive钻石代充 [自动充值] - 10000 钻石', 'images/speed4card/c26c864ec279d1fae9f418110fcd54bd.jpeg', 246.13, 246.13, @cat_id_6, 2, 1);
INSERT INTO goods (gd_name, gd_description, gd_keywords, picture, retail_price, actual_price, group_id, type, is_open) VALUES ('BIGO LIVE直播充值 bigolive钻石代充 [自动充值] - 16000 钻石', 'BIGO LIVE直播充值 bigolive钻石代充 [自动充值] 此产品为：BIGO LIVE直播钻石充值，BIGO钻石只能用于直播间送礼物。充值类型：系统自动充值如何发货：付款后1-5分钟内，系统自动充值【BIGO钻石充值】如何收货：登入BIGO LIVE直播，查看钻石余额和明细【BIGO钻石充值】注意事项：1. 购买前请确...', 'BIGO LIVE直播充值 bigolive钻石代充 [自动充值] - 16000 钻石', 'images/speed4card/c26c864ec279d1fae9f418110fcd54bd.jpeg', 390.47, 390.47, @cat_id_6, 2, 1);
INSERT INTO goods (gd_name, gd_description, gd_keywords, picture, retail_price, actual_price, group_id, type, is_open) VALUES ('BIGO LIVE直播充值 bigolive钻石代充 [自动充值] - 20000 钻石', 'BIGO LIVE直播充值 bigolive钻石代充 [自动充值] 此产品为：BIGO LIVE直播钻石充值，BIGO钻石只能用于直播间送礼物。充值类型：系统自动充值如何发货：付款后1-5分钟内，系统自动充值【BIGO钻石充值】如何收货：登入BIGO LIVE直播，查看钻石余额和明细【BIGO钻石充值】注意事项：1. 购买前请确...', 'BIGO LIVE直播充值 bigolive钻石代充 [自动充值] - 20000 钻石', 'images/speed4card/c26c864ec279d1fae9f418110fcd54bd.jpeg', 471.31, 471.31, @cat_id_6, 2, 1);
INSERT INTO goods (gd_name, gd_description, gd_keywords, picture, retail_price, actual_price, group_id, type, is_open) VALUES ('BIGO LIVE直播充值 bigolive钻石代充 [自动充值] - 100 钻石 (SG-MY-AU-NZ)', 'BIGO LIVE直播充值 bigolive钻石代充 [自动充值] 此产品为：BIGO LIVE直播钻石充值，BIGO钻石只能用于直播间送礼物。充值类型：系统自动充值如何发货：付款后1-5分钟内，系统自动充值【BIGO钻石充值】如何收货：登入BIGO LIVE直播，查看钻石余额和明细【BIGO钻石充值】注意事项：1. 购买前请确...', 'BIGO LIVE直播充值 bigolive钻石代充 [自动充值] - 100 钻石 (SG-MY-AU-NZ)', 'images/speed4card/c26c864ec279d1fae9f418110fcd54bd.jpeg', 2.75, 2.75, @cat_id_6, 2, 1);
INSERT INTO goods (gd_name, gd_description, gd_keywords, picture, retail_price, actual_price, group_id, type, is_open) VALUES ('BIGO LIVE直播充值 bigolive钻石代充 [自动充值] - 160 钻石 (SG-MY-AU-NZ)', 'BIGO LIVE直播充值 bigolive钻石代充 [自动充值] 此产品为：BIGO LIVE直播钻石充值，BIGO钻石只能用于直播间送礼物。充值类型：系统自动充值如何发货：付款后1-5分钟内，系统自动充值【BIGO钻石充值】如何收货：登入BIGO LIVE直播，查看钻石余额和明细【BIGO钻石充值】注意事项：1. 购买前请确...', 'BIGO LIVE直播充值 bigolive钻石代充 [自动充值] - 160 钻石 (SG-MY-AU-NZ)', 'images/speed4card/c26c864ec279d1fae9f418110fcd54bd.jpeg', 4.4, 4.4, @cat_id_6, 2, 1);
INSERT INTO goods (gd_name, gd_description, gd_keywords, picture, retail_price, actual_price, group_id, type, is_open) VALUES ('BIGO LIVE直播充值 bigolive钻石代充 [自动充值] - 240 钻石 (SG-MY-AU-NZ)', 'BIGO LIVE直播充值 bigolive钻石代充 [自动充值] 此产品为：BIGO LIVE直播钻石充值，BIGO钻石只能用于直播间送礼物。充值类型：系统自动充值如何发货：付款后1-5分钟内，系统自动充值【BIGO钻石充值】如何收货：登入BIGO LIVE直播，查看钻石余额和明细【BIGO钻石充值】注意事项：1. 购买前请确...', 'BIGO LIVE直播充值 bigolive钻石代充 [自动充值] - 240 钻石 (SG-MY-AU-NZ)', 'images/speed4card/c26c864ec279d1fae9f418110fcd54bd.jpeg', 6.6, 6.6, @cat_id_6, 2, 1);
INSERT INTO goods (gd_name, gd_description, gd_keywords, picture, retail_price, actual_price, group_id, type, is_open) VALUES ('BIGO LIVE直播充值 bigolive钻石代充 [自动充值] - 400 钻石 (SG-MY-AU-NZ)', 'BIGO LIVE直播充值 bigolive钻石代充 [自动充值] 此产品为：BIGO LIVE直播钻石充值，BIGO钻石只能用于直播间送礼物。充值类型：系统自动充值如何发货：付款后1-5分钟内，系统自动充值【BIGO钻石充值】如何收货：登入BIGO LIVE直播，查看钻石余额和明细【BIGO钻石充值】注意事项：1. 购买前请确...', 'BIGO LIVE直播充值 bigolive钻石代充 [自动充值] - 400 钻石 (SG-MY-AU-NZ)', 'images/speed4card/c26c864ec279d1fae9f418110fcd54bd.jpeg', 10.54, 10.54, @cat_id_6, 2, 1);
INSERT INTO goods (gd_name, gd_description, gd_keywords, picture, retail_price, actual_price, group_id, type, is_open) VALUES ('BIGO LIVE直播充值 bigolive钻石代充 [自动充值] - 500 钻石 (SG-MY-AU-NZ)', 'BIGO LIVE直播充值 bigolive钻石代充 [自动充值] 此产品为：BIGO LIVE直播钻石充值，BIGO钻石只能用于直播间送礼物。充值类型：系统自动充值如何发货：付款后1-5分钟内，系统自动充值【BIGO钻石充值】如何收货：登入BIGO LIVE直播，查看钻石余额和明细【BIGO钻石充值】注意事项：1. 购买前请确...', 'BIGO LIVE直播充值 bigolive钻石代充 [自动充值] - 500 钻石 (SG-MY-AU-NZ)', 'images/speed4card/c26c864ec279d1fae9f418110fcd54bd.jpeg', 13.17, 13.17, @cat_id_6, 2, 1);
INSERT INTO goods (gd_name, gd_description, gd_keywords, picture, retail_price, actual_price, group_id, type, is_open) VALUES ('BIGO LIVE直播充值 bigolive钻石代充 [自动充值] - 800 钻石 (SG-MY-AU-NZ)', 'BIGO LIVE直播充值 bigolive钻石代充 [自动充值] 此产品为：BIGO LIVE直播钻石充值，BIGO钻石只能用于直播间送礼物。充值类型：系统自动充值如何发货：付款后1-5分钟内，系统自动充值【BIGO钻石充值】如何收货：登入BIGO LIVE直播，查看钻石余额和明细【BIGO钻石充值】注意事项：1. 购买前请确...', 'BIGO LIVE直播充值 bigolive钻石代充 [自动充值] - 800 钻石 (SG-MY-AU-NZ)', 'images/speed4card/c26c864ec279d1fae9f418110fcd54bd.jpeg', 20.15, 20.15, @cat_id_6, 2, 1);
INSERT INTO goods (gd_name, gd_description, gd_keywords, picture, retail_price, actual_price, group_id, type, is_open) VALUES ('BIGO LIVE直播充值 bigolive钻石代充 [自动充值] - 1000 钻石 (SG-MY-AU-NZ)', 'BIGO LIVE直播充值 bigolive钻石代充 [自动充值] 此产品为：BIGO LIVE直播钻石充值，BIGO钻石只能用于直播间送礼物。充值类型：系统自动充值如何发货：付款后1-5分钟内，系统自动充值【BIGO钻石充值】如何收货：登入BIGO LIVE直播，查看钻石余额和明细【BIGO钻石充值】注意事项：1. 购买前请确...', 'BIGO LIVE直播充值 bigolive钻石代充 [自动充值] - 1000 钻石 (SG-MY-AU-NZ)', 'images/speed4card/c26c864ec279d1fae9f418110fcd54bd.jpeg', 25.19, 25.19, @cat_id_6, 2, 1);
INSERT INTO goods (gd_name, gd_description, gd_keywords, picture, retail_price, actual_price, group_id, type, is_open) VALUES ('BIGO LIVE直播充值 bigolive钻石代充 [自动充值] - 2000 钻石 (SG-MY-AU-NZ)', 'BIGO LIVE直播充值 bigolive钻石代充 [自动充值] 此产品为：BIGO LIVE直播钻石充值，BIGO钻石只能用于直播间送礼物。充值类型：系统自动充值如何发货：付款后1-5分钟内，系统自动充值【BIGO钻石充值】如何收货：登入BIGO LIVE直播，查看钻石余额和明细【BIGO钻石充值】注意事项：1. 购买前请确...', 'BIGO LIVE直播充值 bigolive钻石代充 [自动充值] - 2000 钻石 (SG-MY-AU-NZ)', 'images/speed4card/c26c864ec279d1fae9f418110fcd54bd.jpeg', 50.38, 50.38, @cat_id_6, 2, 1);
INSERT INTO goods (gd_name, gd_description, gd_keywords, picture, retail_price, actual_price, group_id, type, is_open) VALUES ('BIGO LIVE直播充值 bigolive钻石代充 [自动充值] - 4000 钻石 (SG-MY-AU-NZ)', 'BIGO LIVE直播充值 bigolive钻石代充 [自动充值] 此产品为：BIGO LIVE直播钻石充值，BIGO钻石只能用于直播间送礼物。充值类型：系统自动充值如何发货：付款后1-5分钟内，系统自动充值【BIGO钻石充值】如何收货：登入BIGO LIVE直播，查看钻石余额和明细【BIGO钻石充值】注意事项：1. 购买前请确...', 'BIGO LIVE直播充值 bigolive钻石代充 [自动充值] - 4000 钻石 (SG-MY-AU-NZ)', 'images/speed4card/c26c864ec279d1fae9f418110fcd54bd.jpeg', 100.76, 100.76, @cat_id_6, 2, 1);
INSERT INTO goods (gd_name, gd_description, gd_keywords, picture, retail_price, actual_price, group_id, type, is_open) VALUES ('BIGO LIVE直播充值 bigolive钻石代充 [自动充值] - 8000 钻石 (SG-MY-AU-NZ)', 'BIGO LIVE直播充值 bigolive钻石代充 [自动充值] 此产品为：BIGO LIVE直播钻石充值，BIGO钻石只能用于直播间送礼物。充值类型：系统自动充值如何发货：付款后1-5分钟内，系统自动充值【BIGO钻石充值】如何收货：登入BIGO LIVE直播，查看钻石余额和明细【BIGO钻石充值】注意事项：1. 购买前请确...', 'BIGO LIVE直播充值 bigolive钻石代充 [自动充值] - 8000 钻石 (SG-MY-AU-NZ)', 'images/speed4card/c26c864ec279d1fae9f418110fcd54bd.jpeg', 201.52, 201.52, @cat_id_6, 2, 1);
INSERT INTO goods (gd_name, gd_description, gd_keywords, picture, retail_price, actual_price, group_id, type, is_open) VALUES ('BIGO LIVE直播充值 bigolive钻石代充 [自动充值] - 10000 钻石 (SG-MY-AU-NZ)', 'BIGO LIVE直播充值 bigolive钻石代充 [自动充值] 此产品为：BIGO LIVE直播钻石充值，BIGO钻石只能用于直播间送礼物。充值类型：系统自动充值如何发货：付款后1-5分钟内，系统自动充值【BIGO钻石充值】如何收货：登入BIGO LIVE直播，查看钻石余额和明细【BIGO钻石充值】注意事项：1. 购买前请确...', 'BIGO LIVE直播充值 bigolive钻石代充 [自动充值] - 10000 钻石 (SG-MY-AU-NZ)', 'images/speed4card/c26c864ec279d1fae9f418110fcd54bd.jpeg', 251.9, 251.9, @cat_id_6, 2, 1);
INSERT INTO goods (gd_name, gd_description, gd_keywords, picture, retail_price, actual_price, group_id, type, is_open) VALUES ('BIGO LIVE直播充值 bigolive钻石代充 [自动充值] - 16000 钻石 (SG-MY-AU-NZ)', 'BIGO LIVE直播充值 bigolive钻石代充 [自动充值] 此产品为：BIGO LIVE直播钻石充值，BIGO钻石只能用于直播间送礼物。充值类型：系统自动充值如何发货：付款后1-5分钟内，系统自动充值【BIGO钻石充值】如何收货：登入BIGO LIVE直播，查看钻石余额和明细【BIGO钻石充值】注意事项：1. 购买前请确...', 'BIGO LIVE直播充值 bigolive钻石代充 [自动充值] - 16000 钻石 (SG-MY-AU-NZ)', 'images/speed4card/c26c864ec279d1fae9f418110fcd54bd.jpeg', 399.39, 399.39, @cat_id_6, 2, 1);
INSERT INTO goods (gd_name, gd_description, gd_keywords, picture, retail_price, actual_price, group_id, type, is_open) VALUES ('BIGO LIVE直播充值 bigolive钻石代充 [自动充值] - 24000 钻石 (SG-MY-AU-NZ)', 'BIGO LIVE直播充值 bigolive钻石代充 [自动充值] 此产品为：BIGO LIVE直播钻石充值，BIGO钻石只能用于直播间送礼物。充值类型：系统自动充值如何发货：付款后1-5分钟内，系统自动充值【BIGO钻石充值】如何收货：登入BIGO LIVE直播，查看钻石余额和明细【BIGO钻石充值】注意事项：1. 购买前请确...', 'BIGO LIVE直播充值 bigolive钻石代充 [自动充值] - 24000 钻石 (SG-MY-AU-NZ)', 'images/speed4card/c26c864ec279d1fae9f418110fcd54bd.jpeg', 599.07, 599.07, @cat_id_6, 2, 1);

-- Category: 国服手游充值
INSERT INTO goods_group (gp_name, is_open, ord) VALUES ('国服手游充值', 1, 1);
SET @cat_id_7 = LAST_INSERT_ID();

-- Category: 全球话费流量充值
INSERT INTO goods_group (gp_name, is_open, ord) VALUES ('全球话费流量充值', 1, 1);
SET @cat_id_8 = LAST_INSERT_ID();

-- Category: 音乐小说网盘会员
INSERT INTO goods_group (gp_name, is_open, ord) VALUES ('音乐小说网盘会员', 1, 1);
SET @cat_id_9 = LAST_INSERT_ID();
INSERT INTO goods (gd_name, gd_description, gd_keywords, picture, retail_price, actual_price, group_id, type, is_open) VALUES ('1$ VIP 链接 - 任意金额', '1$ VIP 链接 服务描述：1、这是1美元的VIP快捷付款链接，用于speed4game及speed4card网站的会员付款。2、比如您的订单金额是100$，请拍100件，即付款100$。3、详情请咨询您的VIP一对一客服代表。', '1$ VIP 链接 - 任意金额', 'images/speed4card/7fd4abfc8955abd5ad79cf38b9efbd37.png', 0.19, 0.19, @cat_id_9, 2, 1);
INSERT INTO goods (gd_name, gd_description, gd_keywords, picture, retail_price, actual_price, group_id, type, is_open) VALUES ('新浪微博会员(代充) - VIP一个月', '新浪微博会员(代充) 本产品用于网易微博会员充值。充值类型：系统自动发送卡密。卡密如何使用：登录搜狐视频&rarr;点击会员中心&rarr; 点兑换码，输入兑换码&rarr;激活成功，开启搜狐视频黄金会员购买流程：选择所需产品及数量&rarr; 提交订单，登录会员&rarr;付款成...', '新浪微博会员(代充) - VIP一个月', 'images/speed4card/4f2b5ce9c4a0e0176b895c015bddb34d.png', 2.77, 2.77, @cat_id_9, 2, 1);
INSERT INTO goods (gd_name, gd_description, gd_keywords, picture, retail_price, actual_price, group_id, type, is_open) VALUES ('新浪微博会员(代充) - VIP三个月', '新浪微博会员(代充) 本产品用于网易微博会员充值。充值类型：系统自动发送卡密。卡密如何使用：登录搜狐视频&rarr;点击会员中心&rarr; 点兑换码，输入兑换码&rarr;激活成功，开启搜狐视频黄金会员购买流程：选择所需产品及数量&rarr; 提交订单，登录会员&rarr;付款成...', '新浪微博会员(代充) - VIP三个月', 'images/speed4card/4f2b5ce9c4a0e0176b895c015bddb34d.png', 5.73, 5.73, @cat_id_9, 2, 1);
INSERT INTO goods (gd_name, gd_description, gd_keywords, picture, retail_price, actual_price, group_id, type, is_open) VALUES ('新浪微博会员(代充) - VIP十二个月', '新浪微博会员(代充) 本产品用于网易微博会员充值。充值类型：系统自动发送卡密。卡密如何使用：登录搜狐视频&rarr;点击会员中心&rarr; 点兑换码，输入兑换码&rarr;激活成功，开启搜狐视频黄金会员购买流程：选择所需产品及数量&rarr; 提交订单，登录会员&rarr;付款成...', '新浪微博会员(代充) - VIP十二个月', 'images/speed4card/4f2b5ce9c4a0e0176b895c015bddb34d.png', 18.38, 18.38, @cat_id_9, 2, 1);
INSERT INTO goods (gd_name, gd_description, gd_keywords, picture, retail_price, actual_price, group_id, type, is_open) VALUES ('新浪微博会员(代充) - SVIP月卡', '新浪微博会员(代充) 本产品用于网易微博会员充值。充值类型：系统自动发送卡密。卡密如何使用：登录搜狐视频&rarr;点击会员中心&rarr; 点兑换码，输入兑换码&rarr;激活成功，开启搜狐视频黄金会员购买流程：选择所需产品及数量&rarr; 提交订单，登录会员&rarr;付款成...', '新浪微博会员(代充) - SVIP月卡', 'images/speed4card/4f2b5ce9c4a0e0176b895c015bddb34d.png', 5.35, 5.35, @cat_id_9, 2, 1);
INSERT INTO goods (gd_name, gd_description, gd_keywords, picture, retail_price, actual_price, group_id, type, is_open) VALUES ('新浪微博会员(代充) - SVIP季卡', '新浪微博会员(代充) 本产品用于网易微博会员充值。充值类型：系统自动发送卡密。卡密如何使用：登录搜狐视频&rarr;点击会员中心&rarr; 点兑换码，输入兑换码&rarr;激活成功，开启搜狐视频黄金会员购买流程：选择所需产品及数量&rarr; 提交订单，登录会员&rarr;付款成...', '新浪微博会员(代充) - SVIP季卡', 'images/speed4card/4f2b5ce9c4a0e0176b895c015bddb34d.png', 12.44, 12.44, @cat_id_9, 2, 1);
INSERT INTO goods (gd_name, gd_description, gd_keywords, picture, retail_price, actual_price, group_id, type, is_open) VALUES ('新浪微博会员(代充) - SVIP年卡', '新浪微博会员(代充) 本产品用于网易微博会员充值。充值类型：系统自动发送卡密。卡密如何使用：登录搜狐视频&rarr;点击会员中心&rarr; 点兑换码，输入兑换码&rarr;激活成功，开启搜狐视频黄金会员购买流程：选择所需产品及数量&rarr; 提交订单，登录会员&rarr;付款成...', '新浪微博会员(代充) - SVIP年卡', 'images/speed4card/4f2b5ce9c4a0e0176b895c015bddb34d.png', 41.67, 41.67, @cat_id_9, 2, 1);
INSERT INTO goods (gd_name, gd_description, gd_keywords, picture, retail_price, actual_price, group_id, type, is_open) VALUES ('新浪微博会员(代充) - 升级SVIP一个月', '新浪微博会员(代充) 本产品用于网易微博会员充值。充值类型：系统自动发送卡密。卡密如何使用：登录搜狐视频&rarr;点击会员中心&rarr; 点兑换码，输入兑换码&rarr;激活成功，开启搜狐视频黄金会员购买流程：选择所需产品及数量&rarr; 提交订单，登录会员&rarr;付款成...', '新浪微博会员(代充) - 升级SVIP一个月', 'images/speed4card/4f2b5ce9c4a0e0176b895c015bddb34d.png', 1.72, 1.72, @cat_id_9, 2, 1);
INSERT INTO goods (gd_name, gd_description, gd_keywords, picture, retail_price, actual_price, group_id, type, is_open) VALUES ('新浪微博会员(代充) - 升级SVIP三个月', '新浪微博会员(代充) 本产品用于网易微博会员充值。充值类型：系统自动发送卡密。卡密如何使用：登录搜狐视频&rarr;点击会员中心&rarr; 点兑换码，输入兑换码&rarr;激活成功，开启搜狐视频黄金会员购买流程：选择所需产品及数量&rarr; 提交订单，登录会员&rarr;付款成...', '新浪微博会员(代充) - 升级SVIP三个月', 'images/speed4card/4f2b5ce9c4a0e0176b895c015bddb34d.png', 5.16, 5.16, @cat_id_9, 2, 1);
INSERT INTO goods (gd_name, gd_description, gd_keywords, picture, retail_price, actual_price, group_id, type, is_open) VALUES ('新浪微博会员(代充) - 升级SVIP一年', '新浪微博会员(代充) 本产品用于网易微博会员充值。充值类型：系统自动发送卡密。卡密如何使用：登录搜狐视频&rarr;点击会员中心&rarr; 点兑换码，输入兑换码&rarr;激活成功，开启搜狐视频黄金会员购买流程：选择所需产品及数量&rarr; 提交订单，登录会员&rarr;付款成...', '新浪微博会员(代充) - 升级SVIP一年', 'images/speed4card/4f2b5ce9c4a0e0176b895c015bddb34d.png', 18.91, 18.91, @cat_id_9, 2, 1);

-- Category: 游戏平台代付
INSERT INTO goods_group (gp_name, is_open, ord) VALUES ('游戏平台代付', 1, 1);
SET @cat_id_10 = LAST_INSERT_ID();
INSERT INTO goods (gd_name, gd_description, gd_keywords, picture, retail_price, actual_price, group_id, type, is_open) VALUES ('DD373代购 | 嘟嘟游戏圈代购 [人工代购] - 任意金额', 'DD373代购 | 嘟嘟游戏圈代购 [人工代购] DD373网络游戏交易平台代购代付，手机端嘟嘟游戏圈APP代购代付。发货方式：人工代购如何发货：1. 付款后，请联系在线客服，确认您所需代购商品的地址链接；2. 客服根据您提供的商品链接，登陆DD373平台，为您完成代购。DD373代购，如何收货：1....', 'DD373代购 | 嘟嘟游戏圈代购 [人工代购] - 任意金额', 'images/speed4card/6a4eb3c18a37613b0e7e90edb31590f6.jpeg', 0.19, 0.19, @cat_id_10, 2, 1);
INSERT INTO goods (gd_name, gd_description, gd_keywords, picture, retail_price, actual_price, group_id, type, is_open) VALUES ('交易猫代购 - 任意金额', '交易猫代购 产品描述：适用于交易猫网络游戏交易平台旗下的所有产品代付。发货方式：即时代付，即时购买如何发货：1. 付款成功后，请联系在线客服，确认您要代购或代付款的地址是否正确。2. 客服根据您提供的商品链接和账号密码，登陆平台，为您完成代购如...', '交易猫代购 - 任意金额', 'images/speed4card/10f25c8fc1f9bd32a6cf3070a9e39028.jpeg', 0.21, 0.21, @cat_id_10, 2, 1);
INSERT INTO goods (gd_name, gd_description, gd_keywords, picture, retail_price, actual_price, group_id, type, is_open) VALUES ('淘手游代购 - 任意金额', '淘手游代购 产品描述：适用于淘手游网络游戏交易平台旗下的所有产品代付。发货方式：即时代付，即时购买如何发货：1. 付款成功后，请联系在线客服，确认您要代购或代付款的地址是否正确。2. 客服根据您提供的商品链接和账号密码，登陆平台，为您完成代购如...', '淘手游代购 - 任意金额', 'images/speed4card/4bd81e5a565ee378cc233e08dbb10ad6.jpeg', 0.19, 0.19, @cat_id_10, 2, 1);
